# Generated by Django 2.1.5 on 2022-03-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Internal Data',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Comment', models.CharField(max_length=300)),
                ('internalData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_fit.InternalData')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=500)),
                ('Link', models.CharField(max_length=30)),
                ('internalData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_fit.InternalData')),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='University_Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=500)),
                ('internalData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_fit.InternalData')),
            ],
            options={
                'verbose_name_plural': 'University_Departments',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('DepartmentPreference', models.CharField(max_length=100)),
                ('SubjectPreference', models.CharField(max_length=100)),
                ('FavouriteUnversity', models.CharField(max_length=50)),
                ('internalData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_fit.InternalData')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
