# Generated by Django 2.1.5 on 2022-03-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0002_internaldata_review_university_university_department_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='UniName',
            field=models.CharField(default='TestName', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='university_department',
            name='UniId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='uni_fit.University'),
        ),
    ]
