# Generated by Django 2.1.5 on 2022-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0003_auto_20220318_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='id',
        ),
        migrations.RemoveField(
            model_name='university_department',
            name='id',
        ),
        migrations.AddField(
            model_name='university',
            name='UniId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='university_department',
            name='DeptId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
