# Generated by Django 2.1.5 on 2022-03-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0004_auto_20220318_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='UniRank',
            field=models.IntegerField(default=0),
        ),
    ]
