# Generated by Django 2.1.5 on 2022-03-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0005_university_unirank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='FavouriteUnversity',
        ),
        migrations.AddField(
            model_name='users',
            name='FavouriteUnversity',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='uni_fit.University'),
        ),
    ]
