# Generated by Django 2.1.5 on 2022-03-19 03:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0007_auto_20220319_0208'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='university',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
