# Generated by Django 2.1.5 on 2022-03-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0008_auto_20220319_0354'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='university',
            managers=[
            ],
        ),
    ]
