# Generated by Django 2.1.5 on 2022-03-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0010_auto_20220320_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubReddit', models.CharField(max_length=100)),
                ('Link', models.CharField(max_length=500)),
                ('UniName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_fit.University')),
                ('internalData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_fit.InternalData')),
            ],
            options={
                'verbose_name_plural': 'Reddits',
            },
        ),
        migrations.RemoveField(
            model_name='university_department',
            name='About',
        ),
    ]
