# Generated by Django 2.1.5 on 2022-03-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0011_auto_20220320_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddit',
            name='internalData',
        ),
        migrations.RemoveField(
            model_name='review',
            name='internalData',
        ),
        migrations.RemoveField(
            model_name='university',
            name='internalData',
        ),
        migrations.RemoveField(
            model_name='university_department',
            name='internalData',
        ),
        migrations.RemoveField(
            model_name='users',
            name='internalData',
        ),
        migrations.DeleteModel(
            name='InternalData',
        ),
    ]
