# Generated by Django 2.1.5 on 2022-03-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0012_auto_20220320_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_department',
            name='DeptRank',
            field=models.IntegerField(default=0),
        ),
    ]
