# Generated by Django 2.1.5 on 2022-03-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0013_university_department_deptrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='UniId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university_department',
            name='DeptId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
