# Generated by Django 2.1.5 on 2022-03-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0014_auto_20220320_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university_department',
            old_name='UniId',
            new_name='UniName',
        ),
    ]
