# Generated by Django 2.2 on 2022-03-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0015_auto_20220321_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='uni',
        ),
    ]
