# Generated by Django 2.1.5 on 2022-03-22 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0016_auto_20220321_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='FavouriteUnversity',
        ),
        migrations.AddField(
            model_name='university',
            name='FavouriteUnversity',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='uni_fit.Users'),
        ),
    ]
