# Generated by Django 2.1.5 on 2022-03-23 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_fit', '0018_auto_20220322_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='FavouriteUnversity',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
